services:
  # 0. Load balancer (Nginx)
  gwhisp-balancer:
    image: gwhisp/lb
    
    ports:
      - "80:80"

    expose:
      - "80"
      
    depends_on:
      - gwhisp-frontend
      - gwhisp-backend

    networks:
      - app-net
  # 1. Frontend WebGUI Service
  gwhisp-frontend:
    image: gwhisp/frontend
    
    expose:
      - "80" # make it available for other containers to allow front-back communication

    ports:
      - "8090:80"
    networks:
      - app-net
  
  gwhisp-backend:
    image: gwhisp/backend
    
    expose: 
      - 3000 # api
      - 3333 # wordpress

    depends_on:
      - gwhisp-worker

    networks:
      - app-net

  gwhisp-worker:
    image: gwhisp/worker
    expose:
      - 8080

    ports:
      - "9999:8080"

    networks:
      - app-net

networks:
  app-net:
    driver: bridge